bubblewrap
mise
nnn
openssh
tmux
git
wget
curl
tar
zip
unzip
tree
dust
btop
fastfetch
rsync
rclone
restic
gocryptfs
fuse3
reflector
pacman-contrib
lsof
nmap
tcpdump
bash-completion
man-db
words
python-pip
gcr
oath-toolkit
qrencode
zbar
