sshs
git-delta
aichat
age
rage-encryption
age-plugin-yubikey
pwgen
jq
github-cli
croc
tldr
yazi
trash-cli
fd
fzf
ripgrep
bat
zoxide
neovim
glow
uv
pixi
nodejs
npm
python-pynvim
lazygit
lazydocker
starship
duckdb
