gnome-shell
gnome-control-center
gnome-backgrounds
gnome-keyring
gnome-shell-extension-appindicator
dconf-editor
xdg-user-dirs-gtk
xdg-desktop-portal-gnome
gdm
nautilus
evince
gnome-text-editor
gnome-calculator
gnome-calendar
gnome-disk-utility
cups
print-manager
system-config-printer
simple-scan
