niri
swaylock
swayidle
swaybg
pantheon-polkit-agent
fuzzel
mako
vimiv
waybar
gnome-keyring
xdg-desktop-portal-gtk
xwayland-satellite
dconf-editor
nwg-look
breeze-gtk
python-pyqt6
qt5-wayland
qt6-wayland
qt5ct
qt6ct
kvantum
kvantum-qt5
