firefox
mesa
wl-clipboard
cliphist
wtype
rage-encryption
age-plugin-yubikey
yubikey-manager
ccid
pcsclite
pcsc-tools
libfido2
pam-u2f
stow
udisks2
udiskie
libappindicator
tinyxxd
bitwarden
keepassxc
wireguard-tools
sshfs
dosfstools
exfatprogs
handlr-regex
zathura
zathura-pdf-mupdf
mpv
power-profiles-daemon
brightnessctl
alacritty
polkit
gnome-firmware
libnotify
xdg-utils
remmina
freerdp
libreoffice-fresh
noto-fonts
noto-fonts-emoji
ttf-hack-nerd
ttf-firacode-nerd
ttf-jetbrains-mono
ttf-jetbrains-mono-nerd
ttf-nerd-fonts-symbols
ttf-nerd-fonts-symbols-mono
woff2-font-awesome
pipewire
pipewire-alsa
pipewire-pulse
wireplumber
pamixer
pavucontrol
alsa-utils
alsa-firmware
sof-firmware
android-tools
android-udev
